# Generated by Django 4.1 on 2022-08-30 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_alter_orderitem_order'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='orderitem',
            unique_together={('order', 'product')},
        ),
    ]
